import { useRoute } from '@react-navigation/native';
import React, { useRef, useState } from 'react';
import { Alert, Clipboard, Dimensions, Platform, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';

const { width } = Dimensions.get('window');

export default function ResultScreen() {
  const route = useRoute();
  const { result, pattern } = route.params;
  const [isSaving, setIsSaving] = useState(false);
  const patternRef = useRef(null);

  const generatePatternImage = () => {
    // Create a detailed text-based representation that can be saved
    const patternText = pattern.pattern.join('\n');
    const fullText = `╔══════════════════════════════════════╗
║            ${pattern.title.toUpperCase()}            ║
╠══════════════════════════════════════╣
║                                      ║
${pattern.pattern.map(line => `║ ${line.padEnd(36)} ║`).join('\n')}
║                                      ║
╠══════════════════════════════════════╣
║     Generated by Numonics App        ║
║     Result: ${result.toString().padStart(8)}                    ║
╚══════════════════════════════════════╝`;
    return fullText;
  };

  const generateWebImage = () => {
    // For web, create a data URL that can be downloaded
    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');
    
    // Set canvas size
    const cellSize = 20;
    const padding = 40;
    const maxWidth = Math.max(...pattern.pattern.map(line => line.length)) * cellSize;
    const height = pattern.pattern.length * cellSize + padding * 3;
    canvas.width = maxWidth + padding * 2;
    canvas.height = height;
    
    // Background
    ctx.fillStyle = '#ffffff';
    ctx.fillRect(0, 0, canvas.width, canvas.height);
    
    // Border
    ctx.strokeStyle = '#3498db';
    ctx.lineWidth = 3;
    ctx.strokeRect(5, 5, canvas.width - 10, canvas.height - 10);
    
    // Title
    ctx.fillStyle = '#2c3e50';
    ctx.font = 'bold 24px Arial';
    ctx.textAlign = 'center';
    ctx.fillText(pattern.title.toUpperCase(), canvas.width / 2, 35);
    
    // Result
    ctx.font = '16px Arial';
    ctx.fillText(`Result: ${result}`, canvas.width / 2, 60);
    
    // Pattern
    ctx.fillStyle = '#2c3e50';
    const startY = 90;
    const startX = (canvas.width - maxWidth) / 2;
    
    pattern.pattern.forEach((line, rowIndex) => {
      line.split('').forEach((char, colIndex) => {
        if (char === '*') {
          ctx.fillRect(
            startX + colIndex * cellSize,
            startY + rowIndex * cellSize,
            cellSize - 2,
            cellSize - 2
          );
        }
      });
    });
    
    // Footer
    ctx.fillStyle = '#95a5a6';
    ctx.font = '12px Arial';
    ctx.fillText('Generated by Numonics App', canvas.width / 2, height - 15);
    
    return canvas.toDataURL('image/png');
  };

  const savePattern = async () => {
    try {
      setIsSaving(true);
      
      if (Platform.OS === 'web') {
        // For web platform, generate canvas-based image
        try {
          const imageDataUrl = generateWebImage();
          
          // Create download link
          const link = document.createElement('a');
          link.download = `${pattern.title.replace(/\s+/g, '_')}_pattern.png`;
          link.href = imageDataUrl;
          document.body.appendChild(link);
          link.click();
          document.body.removeChild(link);
          
          Alert.alert(
            'Pattern Downloaded!',
            `Your ${pattern.title} pattern has been downloaded as a PNG image.`,
            [
              {
                text: 'Download Again',
                onPress: () => {
                  const link = document.createElement('a');
                  link.download = `${pattern.title.replace(/\s+/g, '_')}_pattern.png`;
                  link.href = imageDataUrl;
                  document.body.appendChild(link);
                  link.click();
                  document.body.removeChild(link);
                },
              },
              {
                text: 'View Text Pattern',
                onPress: () => showPatternDetails(generatePatternImage()),
              },
              {
                text: 'OK',
                style: 'default',
              },
            ]
          );
        } catch (webError) {
          // Fallback to text if canvas fails
          const patternContent = generatePatternImage();
          await Clipboard.setString(patternContent);
          
          Alert.alert(
            'Pattern Copied!',
            `Your ${pattern.title} pattern has been copied to clipboard as text. Canvas generation failed.`,
            [
              {
                text: 'Copy Again',
                onPress: () => Clipboard.setString(patternContent),
              },
              {
                text: 'View Pattern',
                onPress: () => showPatternDetails(patternContent),
              },
              {
                text: 'OK',
                style: 'default',
              },
            ]
          );
        }
      } else {
        // For mobile platforms, try to capture as image
        try {
          const { captureRef } = await import('react-native-view-shot');
          const uri = await captureRef(patternRef, {
            format: 'png',
            quality: 1.0,
          });
          
          await Clipboard.setString(uri);
          
          Alert.alert(
            'Pattern Image Saved!',
            `Your ${pattern.title} pattern has been captured as an image. The image path has been copied to clipboard for sharing.`,
            [
              {
                text: 'Copy Image Path',
                onPress: () => Clipboard.setString(uri),
              },
              {
                text: 'View Pattern',
                onPress: () => showPatternDetails(generatePatternImage()),
              },
              {
                text: 'OK',
                style: 'default',
              },
            ]
          );
        } catch (captureError) {
          // Fallback to text if image capture fails
          const patternContent = generatePatternImage();
          await Clipboard.setString(patternContent);
          
          Alert.alert(
            'Pattern Copied!',
            `Your ${pattern.title} pattern has been copied to clipboard as text. Image capture is not available on this platform.`,
            [
              {
                text: 'Copy Again',
                onPress: () => Clipboard.setString(patternContent),
              },
              {
                text: 'View Pattern',
                onPress: () => showPatternDetails(patternContent),
              },
              {
                text: 'OK',
                style: 'default',
              },
            ]
          );
        }
      }

    } catch (error) {
      console.error('Error saving pattern:', error);
      Alert.alert('Error', 'Failed to save pattern. Please try again.');
    } finally {
      setIsSaving(false);
    }
  };

  const showPatternDetails = (patternContent) => {
    Alert.alert(
      `${pattern.title} Pattern`,
      patternContent,
      [
        {
          text: 'Copy',
          onPress: () => Clipboard.setString(patternContent),
        },
        {
          text: 'Close',
          style: 'cancel',
        },
      ],
      { cancelable: true }
    );
  };


  return (
    <View style={styles.container}>
      <ScrollView contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false}>
        {/* Header Section */}
        <View style={styles.headerSection}>
          <View style={styles.iconContainer}>
            <Text style={styles.icon}>✨</Text>
          </View>
          <Text style={styles.title}>Calculation Complete!</Text>
          <Text style={styles.subtitle}>Your mathematical pattern is ready</Text>
        </View>

        {/* Result Card */}
        <View style={styles.resultCard}>
          <View style={styles.resultHeader}>
            <Text style={styles.resultLabel}>Result</Text>
            <View style={styles.resultValueContainer}>
              <Text style={styles.resultValue}>{result}</Text>
            </View>
          </View>
          <View style={styles.divider} />
          <Text style={styles.resultDescription}>
            This number determines the size and complexity of your pattern
          </Text>
        </View>

        {/* Pattern Section */}
        <View style={styles.patternSection}>
          <View style={styles.patternHeader}>
            <Text style={styles.patternTitle}>{pattern.title}</Text>
            <Text style={styles.patternSubtitle}>Generated Pattern</Text>
          </View>
          
          <View style={styles.patternCard}>
            <View ref={patternRef} style={styles.patternImageContainer}>
              <View style={styles.patternImageHeader}>
                <Text style={styles.patternImageTitle}>{pattern.title}</Text>
                <Text style={styles.patternImageSubtitle}>Result: {result}</Text>
              </View>
              <View style={styles.patternImageContent}>
                {pattern.pattern.map((line, index) => (
                  <View key={index} style={styles.patternImageLine}>
                    {line.split('').map((char, charIndex) => (
                      <View 
                        key={charIndex} 
                        style={[
                          styles.patternImageChar,
                          char === '*' ? styles.patternImageCharFilled : styles.patternImageCharEmpty
                        ]}
                      />
                    ))}
                  </View>
                ))}
              </View>
              <View style={styles.patternImageFooter}>
                <Text style={styles.patternImageFooterText}>Generated by Numonics</Text>
              </View>
            </View>
          </View>

          <View style={styles.patternFooter}>
            <Text style={styles.patternFooterText}>
              Perfect for t-shirt printing! 🎨
            </Text>
          </View>
        </View>

        {/* Action Button */}
        <View style={styles.actionSection}>
          <TouchableOpacity 
            style={[styles.primaryButton, isSaving && styles.disabledButton]} 
            onPress={savePattern}
            disabled={isSaving}
          >
            <Text style={styles.primaryButtonText}>
              {isSaving ? 'Saving...' : Platform.OS === 'web' ? 'Copy Pattern' : 'Save as Image'}
            </Text>
          </TouchableOpacity>
        </View>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f0f8ff',
  },
  scrollContent: {
    paddingTop: 60,
    paddingHorizontal: 20,
    paddingBottom: 30,
    alignItems: 'center',
  },
  
  // Header Section
  headerSection: {
    alignItems: 'center',
    marginBottom: 30,
  },
  iconContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  icon: {
    fontSize: 40,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#2c3e50',
    textAlign: 'center',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 16,
    color: '#7f8c8d',
    textAlign: 'center',
    fontWeight: '500',
  },

  // Result Card
  resultCard: {
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 25,
    width: '100%',
    marginBottom: 30,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  resultHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  resultLabel: {
    fontSize: 18,
    fontWeight: '600',
    color: '#34495e',
  },
  resultValueContainer: {
    backgroundColor: '#3498db',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 25,
    minWidth: 80,
    alignItems: 'center',
  },
  resultValue: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#fff',
  },
  divider: {
    height: 2,
    backgroundColor: '#ecf0f1',
    marginVertical: 15,
  },
  resultDescription: {
    fontSize: 14,
    color: '#7f8c8d',
    textAlign: 'center',
    lineHeight: 20,
  },

  // Pattern Section
  patternSection: {
    width: '100%',
    marginBottom: 30,
  },
  patternHeader: {
    alignItems: 'center',
    marginBottom: 20,
  },
  patternTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#2c3e50',
    textAlign: 'center',
    marginBottom: 5,
  },
  patternSubtitle: {
    fontSize: 14,
    color: '#7f8c8d',
    textAlign: 'center',
    fontWeight: '500',
  },
  patternCard: {
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  patternContainer: {
    backgroundColor: '#f8f9fa',
    borderRadius: 15,
    padding: 20,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#e9ecef',
  },
  patternLine: {
    fontSize: 14,
    fontFamily: 'monospace',
    color: '#2c3e50',
    textAlign: 'center',
    letterSpacing: 2,
    lineHeight: 16,
    marginBottom: 2,
    fontWeight: '600',
  },
  patternFooter: {
    marginTop: 15,
    alignItems: 'center',
  },
  patternFooterText: {
    fontSize: 14,
    color: '#27ae60',
    fontWeight: '600',
    textAlign: 'center',
  },

  // Action Section
  actionSection: {
    width: '100%',
    alignItems: 'center',
  },
  primaryButton: {
    backgroundColor: '#3498db',
    paddingVertical: 15,
    paddingHorizontal: 40,
    borderRadius: 25,
    alignItems: 'center',
    shadowColor: '#3498db',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
    minWidth: 200,
  },
  primaryButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  disabledButton: {
    backgroundColor: '#bdc3c7',
    shadowOpacity: 0,
    elevation: 0,
  },

  // Pattern Image Styles
  patternImageContainer: {
    backgroundColor: '#ffffff',
    borderRadius: 15,
    padding: 20,
    alignItems: 'center',
    minHeight: 300,
    borderWidth: 2,
    borderColor: '#e9ecef',
  },
  patternImageHeader: {
    alignItems: 'center',
    marginBottom: 20,
    paddingBottom: 15,
    borderBottomWidth: 2,
    borderBottomColor: '#3498db',
    width: '100%',
  },
  patternImageTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#2c3e50',
    marginBottom: 5,
  },
  patternImageSubtitle: {
    fontSize: 16,
    color: '#7f8c8d',
    fontWeight: '600',
  },
  patternImageContent: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 20,
  },
  patternImageLine: {
    flexDirection: 'row',
    marginBottom: 2,
  },
  patternImageChar: {
    width: 12,
    height: 12,
    marginHorizontal: 1,
    marginVertical: 1,
  },
  patternImageCharFilled: {
    backgroundColor: '#2c3e50',
    borderRadius: 2,
  },
  patternImageCharEmpty: {
    backgroundColor: 'transparent',
  },
  patternImageFooter: {
    alignItems: 'center',
    marginTop: 20,
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: '#ecf0f1',
    width: '100%',
  },
  patternImageFooterText: {
    fontSize: 12,
    color: '#95a5a6',
    fontWeight: '500',
  },
});
